### ISSUE TITLE
Support ueberzug for image preview 

### ISSUE THREAD

**Issue by siduck** [kamiyaa/joshuto#65] opened 2021-06-05 03:11 UTC
ranger and some other file managers support ueberzug , ueberzug can be used for viewing images , gif and this will work on any terminal , its not terminal specific like w3m :)

https://github.com/seebye/ueberzug

ranger's image preview : 

![image](https://user-images.githubusercontent.com/59060246/120878387-b9295180-c5d9-11eb-97fa-f76e51b80240.png)

**Comment by kamiyaa** [comment] 2021-06-06 01:23
Seems like `ueberzug` utilizes x11 features to accomplish this.
I no longer directly use x11 and it is slowly being phased out, so I'm not too motivated on getting this feature implemented.

However, if anyone else would like to implement this without introducing dependencies on x11, feel free!

**Comment by siduck76** [comment] 2021-06-06 01:45
Oh :( , almost most cli file managers I used did support ueberzug like clifm, lf, vifm etc! ueberzug depends on X yes , But Its the only image viewing protocol or such that works for every terminal unlike w3m , sixel etc , You cant 

![image](https://user-images.githubusercontent.com/59060246/120909798-72e5f800-c696-11eb-8245-5d583f0532f9.png)

**Comment by DLFW** [comment] 2021-06-06 08:52
Hi!
My 2 cents:
I guess an image preview feature will be wanted / needed / demanded by many users and it makes total sense to get it implemented. It's just super useful. On the other hand, I understand that avoiding certain dependencies (and X likely belongs to them) is necessary to keep the project slick, clean and flexible. Unfortunately, showing images in a terminal is something very special and will be hard to realize without some kind of dependency.

But I also guess that most users from the joshuto target audience will be fans of the  “do one thing and do it well” idea and won't have a problem to integrate other programs with some configuration and scripting effort.

So, just a rough idea: What about some kind of script hook when selecting a file?
As soon as we have some textual file preview implemented, we could have a feature that can call a script (on_selection) with the preview field’s starting coordinate, total height, and the number of lines of the textual preview (all in terminal character cells). That would allow that external script to use Ueberzug or another solution like [icat from Kitty](https://sw.kovidgoyal.net/kitty/kittens/icat.html) to show an image. When the file selection changes, another hook-script (“on_deselection”) could be called in where the user could remove the image. Only when this 2nd script terminates, the first one (on_selection) is called again with the currently selected file. (I guess the latter must also be called when joshuto terminates and when tabs change. Also geometry changes must be considered somehow.)

People could do plenty of things with a hook-solution like this and joshuto could document some snippets to easily integrate image previews into joshuto. Joshuto itself wouldn't have any additional dependency or any bloat for this very special image-preview feature.

Any opinions?

**Comment by siduck76** [comment] 2021-06-06 09:25
I dont think using only icat would be good since only kitty users would be able to use it and it'd limit all the non kitty users as well like alacritty , st etc . A file manager being terminal specific like working only for one terminal ( to show images) wouldnt be a good idea ig :/

**Comment by siduck76** [comment] 2021-06-06 09:25
I dont think using only icat would be good since only kitty users would be able to use it and it'd limit all the non kitty users as well like alacritty , st etc . A file manager being terminal specific like working only for one terminal ( to show images) wouldnt be a good idea ig :/

**Comment by DLFW** [comment] 2021-06-06 09:39
Hm, seems I expressed myself not very clearly. I was *not* talking about “only using icat” at all. (I'm not using Kitty myself.) I was talking about using external user-scripts to control a preview program which could be Ueberzug *or* icat *or* anything else which supports drawing an image on the terminal by getting the cell coordinates. I basically proposed to handle the image preview in separate user scripts to keep the dependencies out of joshuto and to gain flexibility for the users.

Was my text that confusing? English is not my native lang but I'm a bit surprised that it's that bad.... :|

**Comment by siduck76** [comment] 2021-06-06 09:46
@DLFW no I did understand what you said! I just got a bit upset when I heard joshuto wouldnt be getting any ueberzug support. I like ranger and it has good image support but its a bit slow! thats why I tried joshuto and its fast but yeah ueberzug needs some support :D

**Comment by kamiyaa** [comment] 2021-06-07 00:02
I've created a new issue to track the progress and discussion on getting file previews to work. https://github.com/kamiyaa/joshuto/issues/67

Unfortunately, I won't have much time to work on this :/

**Comment by DLFW** [comment] 2021-12-20 14:22
I have provided #113 and some documentation how to implement image previes. If somebody can also test the documented recipe, in case this gets merged, that would be great. ;)

**Comment by kamiyaa** [comment] 2021-12-28 13:47
Closed via
https://github.com/kamiyaa/joshuto/pull/113
https://github.com/kamiyaa/joshuto/pull/115

**Closed by kamiyaa** 2021-12-28 13:47 UTC
Labels: enhancement, help wanted

**Comment by siduck** [comment] 2022-01-27 06:55
@kamiyaa  I tried the scripts and it didnt work for me :( 

![image](https://user-images.githubusercontent.com/59060246/151307293-adee8e50-e01d-4665-be46-c5e51c4cef93.png)

**Comment by siduck** [comment] 2022-01-27 06:56
![image](https://user-images.githubusercontent.com/59060246/151307376-0732739f-47ef-4abe-8d4a-c691657275b9.png)

**Comment by siduck** [comment] 2022-01-27 07:03
i had those 2 scripts in my joshuto config's dir and ran this wrapper https://github.com/kamiyaa/joshuto/blob/main/docs/image_previews.md#joshuto-wrapper

**Comment by DLFW** [comment] 2022-01-27 19:20
The problem is not with the hook scripts or the wrapper, but with the basic file preview.
Your screenshot shows that there is not preview area, ergo the preview-shown hook has not been invoked.

You need to configure a preview script, for example `preview_script = "~/.config/joshuto/preview.sh"`. It's not necessary to have this script printing anything to stdout, but it will cause Joshuto to show the preview area. That will trigger the hook script which now has some place to draw its picture on.

**Comment by siduck** [comment] 2022-01-28 01:15
works now! thanks @DLFW 

![image](https://user-images.githubusercontent.com/59060246/151469802-4610584c-ffda-4cfe-84ea-3cdd45093e5e.png)

**Comment by siduck** [comment] 2022-01-28 01:27
but memory usage of ueberzug is way tooo high 
![image](https://user-images.githubusercontent.com/59060246/151470973-01903d3e-fe50-4647-89bc-d875d3185c22.png)

**Comment by DLFW** [comment] 2022-01-28 20:26
Hi,
I compared the mem usage with the Joshuto wrapper and with Ranger and cannot see a difference. Ueberzug's mem usage jumps around (it's garbage collected) but behaves similar in both.

Ueberzug itself is of course out of scope here. If there is no mistake in the wrapper logic, I cannot see what we can do about that.

**Comment by siduck** [comment] 2022-01-29 01:00
> Hi, I compared the mem usage with the Joshuto wrapper and with Ranger and cannot see a difference. Ueberzug's mem usage jumps around (it's garbage collected) but behaves similar in both.
> 
> Ueberzug itself is of course out of scope here. If there is no mistake in the wrapper logic, I cannot see what we can do about that.

yea i tested it with ranger and viewing multiple images with ueberzug sequentially increments its memory size

**Comment by siduck** [comment] 2022-01-29 01:01
https://github.com/Adit-Chauhan/Ueberzug-rs
https://pkg.go.dev/gitlab.com/diamondburned/ueberzug-go

**Comment by Beethoven-n** [comment] 2023-07-07 02:36
so [seebye/ueberzug](https://github.com/seebye/ueberzug) got archived.

good news, [ueberzugpp](https://github.com/jstkdng/ueberzugpp/) has a wayland output method that works with sway, which could mean that wlroots is supported. this might be worth testing further integration

**Comment by DLFW** [comment] 2023-07-09 20:35
Thanks @Beethoven-n for spreading awareness! Interesting... If `ueberzugpp` could act as a single abstraction bin to serve all terminals and X11+Wayland, I also think that it could make sense to think about a “hard” integration for a better out-of-the-box experience for Joshuto users.

However, I had [some problems](https://github.com/jstkdng/ueberzugpp/issues/84) to get Überzug++ running reliably and I saw you [also had some confusion](https://github.com/jstkdng/ueberzugpp/issues/83). If Überzug++ provides no good out-of-the-box experience, Joshuto won't either, when we integrate it.

I just have merge-requested a doc-update for using Überzug++ with Joshuto's hook scripts (#359). I would propose to first check for some time how this project develops and if we stumble across some more user opinions. Maybe some Wayland&Non-Kitty-Users are around to check what out-of-the-box-happiness they experience with Überzug++?

**Comment by Beethoven-n** [comment] 2023-07-14 04:24
ueberzugpp is intended as a drop in replacement for ueberzug. it should function identically for the moment. if all else fails you can just send it a command formatted to json
